
package prociencia2.views.panels;

import prociencia2.logic.core.entities.Ocupacion;
import prociencia2.views.componets.PJTextField;


public class PanelCaseEmpleado extends javax.swing.JPanel implements PanelValidador{

    private final java.util.ResourceBundle RB;
    private final Ocupacion ocupacion = new Ocupacion();
    private final java.awt.Color colorGuia;
    
    public PanelCaseEmpleado(java.util.ResourceBundle RB) {
        this.RB = RB;
        initComponents();
        this.colorGuia = guiaMain.getForeground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Empresa = new PJTextField();
        guiaMain = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cargoLaborado = new PJTextField();
        guia2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nivelEscolaridad = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxSi = new javax.swing.JCheckBox();
        jCheckBoxNo = new javax.swing.JCheckBox();
        parametro = new javax.swing.JLabel();
        jUltimoCurso = new PJTextField(true);
        guia3 = new javax.swing.JLabel();
        jLabelPrograma = new javax.swing.JLabel();
        programa = new PJTextField();
        lugar = new PJTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(getFont());
        jLabel1.setForeground(getForeground());
        jLabel1.setText("Empresa:");

        Empresa.setFont(getFont());
        Empresa.setForeground(getForeground());

        guiaMain.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        guiaMain.setForeground(new java.awt.Color(0, 102, 255));
        guiaMain.setText(RB.getString("GuiaEmpleado"));

        jLabel3.setFont(getFont());
        jLabel3.setForeground(getForeground());
        jLabel3.setText("Cargo desempeñado:");

        cargoLaborado.setFont(getFont());
        cargoLaborado.setForeground(getForeground());

        guia2.setFont(guiaMain.getFont());
        guia2.setForeground(guiaMain.getForeground());
        guia2.setText(RB.getString("GuiaCargo"));

        jLabel2.setFont(getFont());
        jLabel2.setForeground(getForeground());
        jLabel2.setText("Nivel de escolaridad:");

        nivelEscolaridad.setFont(getFont());
        nivelEscolaridad.setForeground(getForeground());
        nivelEscolaridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bachillerato", "Normal Superior", "Técnico", "Tecnológico", "Universitario" }));
        nivelEscolaridad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nivelEscolaridadItemStateChanged(evt);
            }
        });

        jLabel5.setFont(getFont());
        jLabel5.setForeground(getForeground());
        jLabel5.setText("¿Culmino sus estudios?");

        jCheckBoxSi.setBackground(getBackground());
        buttonGroup1.add(jCheckBoxSi);
        jCheckBoxSi.setFont(getFont());
        jCheckBoxSi.setForeground(getForeground());
        jCheckBoxSi.setText("Si");
        jCheckBoxSi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxSiItemStateChanged(evt);
            }
        });

        jCheckBoxNo.setBackground(getBackground());
        buttonGroup1.add(jCheckBoxNo);
        jCheckBoxNo.setFont(getFont());
        jCheckBoxNo.setForeground(getForeground());
        jCheckBoxNo.setText("No");
        jCheckBoxNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxNoItemStateChanged(evt);
            }
        });

        parametro.setFont(getFont());
        parametro.setForeground(getForeground());
        parametro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jUltimoCurso.setFont(getFont());
        jUltimoCurso.setForeground(getForeground());
        jUltimoCurso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jUltimoCurso.setVisible(false);

        guia3.setFont(guiaMain.getFont());
        guia3.setForeground(guiaMain.getForeground());

        jLabelPrograma.setFont(getFont());
        jLabelPrograma.setForeground(getForeground());
        jLabelPrograma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        programa.setFont(getFont());
        programa.setForeground(getForeground());
        programa.setVisible(false);

        lugar.setFont(getFont());
        lugar.setForeground(getForeground());
        lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarActionPerformed(evt);
            }
        });

        jLabel4.setFont(getFont());
        jLabel4.setForeground(getForeground());
        jLabel4.setText("Lugar de Registro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargoLaborado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guiaMain, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(guia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parametro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUltimoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guia3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nivelEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(programa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(guiaMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoLaborado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(nivelEscolaridad)
                    .addComponent(jLabelPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guia3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUltimoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jCheckBoxSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parametro, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxNoItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            parametro.setText((nivelEscolaridad.getSelectedIndex() == 0)?
                    RB.getString("labelEscoB"):RB.getString("labelEscoS"));
            guia3.setText(
                    (nivelEscolaridad.getSelectedIndex() == 0)?
                    RB.getString("GuiaUltimoGrado"):RB.getString("GuiaUltimoSemes")
            );
          
            jUltimoCurso.setVisible(true);
        }
    }//GEN-LAST:event_jCheckBoxNoItemStateChanged

    private void nivelEscolaridadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nivelEscolaridadItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            if(jCheckBoxNo.isSelected()){
                parametro.setText((nivelEscolaridad.getSelectedIndex() == 0)?
                    RB.getString("labelEscoB"):RB.getString("labelEscoS"));
                guia3.setText(
                    (nivelEscolaridad.getSelectedIndex() == 0)?
                    RB.getString("GuiaUltimoGrado"):RB.getString("GuiaUltimoSemes")
                );
            }
            if(nivelEscolaridad.getSelectedIndex() >= 2 && nivelEscolaridad.getSelectedIndex() <= 4){
                jLabelPrograma.setText("Programa:");
                programa.setVisible(true);
            }else{
                jLabelPrograma.setText("");
                programa.setVisible(false);
            }
        }
    }//GEN-LAST:event_nivelEscolaridadItemStateChanged

    private void jCheckBoxSiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxSiItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            parametro.setText("");
            guia3.setText("");
            jUltimoCurso.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxSiItemStateChanged

    private void lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarActionPerformed

    public boolean camposVacios() {
        if(((PJTextField)Empresa).fieldEmply() || ((PJTextField)cargoLaborado).fieldEmply() || ((PJTextField)lugar).fieldEmply()){
            return true;
        }else if((nivelEscolaridad.getSelectedIndex() >= 2 && nivelEscolaridad.getSelectedIndex() <= 4) && ((PJTextField)programa).fieldEmply()){
            return true;
        }else if(!jCheckBoxSi.isSelected() && !jCheckBoxNo.isSelected()){
            return true;
        }else
            return jCheckBoxNo.isSelected() && ((PJTextField)jUltimoCurso).fieldEmply();
    }

    public void throwWarning() {
        javax.swing.JOptionPane.showMessageDialog(this, RB.getString("WarningGene"),"Datos incompletos",javax.swing.JOptionPane.WARNING_MESSAGE,
             new javax.swing.ImageIcon(getClass().getResource("/prociencia2/views/resources/Attention.png")));
    }

    public Ocupacion getOcupacion() {
        ocupacion.setInstitucion(Empresa.getText());
        ocupacion.setGradoCursado(null);
        ocupacion.setCargo(cargoLaborado.getText());
        ocupacion.setNivelEscolaridad(nivelEscolaridad.getSelectedItem().toString());
        ocupacion.setPrograma(programa.getText());
        ocupacion.setCulmino(jCheckBoxSi.isSelected());
        ocupacion.setUltimoGrado((jCheckBoxSi.isSelected())? null: Integer.parseInt(((jUltimoCurso.getText().compareTo(""))==0)? "0":jUltimoCurso.getText()));
        return ocupacion;
    }

    public String getLugar() {
        return lugar.getText().compareTo("") == 0 ? null : lugar.getText();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Empresa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cargoLaborado;
    private javax.swing.JLabel guia2;
    private javax.swing.JLabel guia3;
    private javax.swing.JLabel guiaMain;
    private javax.swing.JCheckBox jCheckBoxNo;
    private javax.swing.JCheckBox jCheckBoxSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPrograma;
    private javax.swing.JTextField jUltimoCurso;
    private javax.swing.JTextField lugar;
    private javax.swing.JComboBox nivelEscolaridad;
    private javax.swing.JLabel parametro;
    private javax.swing.JTextField programa;
    // End of variables declaration//GEN-END:variables
}
