
package prociencia2.views.panels;

import prociencia2.logic.core.daos.AdministradorDao;

/**
 *
 * @author Klac
 */
public class PanelConfigPass extends javax.swing.JPanel {

    private java.awt.event.KeyAdapter keyListener;
    private final javax.swing.JDialog parent;
    /**
     * Creates new form PanelConfigPass
     * @param parent
     */
    public PanelConfigPass(javax.swing.JDialog parent) {
        this.parent = parent;
        this.setBackground(java.awt.Color.WHITE);
        initComponents();
    }

    private java.awt.event.KeyAdapter createKeyAdapter(){
        if(keyListener == null){
            keyListener = new java.awt.event.KeyAdapter() {
                @Override
                public void keyReleased(java.awt.event.KeyEvent evt){
                    jButton1.setEnabled(verificFields());
                    if(verificFields()){
                        if(jTextFieldNew.getText().compareTo(jTextFieldConfir.getText()) != 0){
                            jLabelVeri.setText("Contraseñas no coinciden");
                        }else{
                            jLabelVeri.setText("");
                        }
                        jButton1.setEnabled(jTextFieldNew.getText().compareTo(jTextFieldConfir.getText()) == 0);
                    }
                }
            };
        }
        return keyListener;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldActual = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNew = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldConfir = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabelVeri = new javax.swing.JLabel();

        jLabel1.setBackground(this.getBackground());
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Contraseña actual");

        jTextFieldActual.setFont(jLabel1.getFont());
        jTextFieldActual.setForeground(jLabel1.getForeground());
        jTextFieldActual.addKeyListener(createKeyAdapter());

        jLabel2.setBackground(jLabel1.getBackground());
        jLabel2.setFont(jLabel1.getFont());
        jLabel2.setForeground(jLabel1.getForeground());
        jLabel2.setText("Contraseña nueva");

        jTextFieldNew.setFont(jLabel1.getFont());
        jTextFieldNew.setForeground(jLabel1.getForeground());
        jTextFieldNew.addKeyListener(createKeyAdapter());

        jLabel3.setBackground(jLabel1.getBackground());
        jLabel3.setFont(jLabel1.getFont());
        jLabel3.setForeground(jLabel1.getForeground());
        jLabel3.setText("Confirmar contraseña");

        jTextFieldConfir.setFont(jLabel1.getFont());
        jTextFieldConfir.setForeground(jLabel1.getForeground());
        jTextFieldConfir.addKeyListener(createKeyAdapter());

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(jLabel1.getFont());
        jButton1.setForeground(jLabel1.getForeground());
        jButton1.setText("Aceptar");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelVeri.setBackground(jLabel1.getBackground());
        jLabelVeri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVeri.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelVeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldActual)
                            .addComponent(jTextFieldNew)
                            .addComponent(jTextFieldConfir, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNew, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConfir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVeri, javax.swing.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdministradorDao usuarioDao = new AdministradorDao();
        try {
            if(usuarioDao.updatePassword(jTextFieldActual.getText(), jTextFieldConfir.getText())){
                javax.swing.JOptionPane.showMessageDialog(this, "Contraseña actualizada");
                doClose();
            }else{
                 javax.swing.JOptionPane.showMessageDialog(this, "La contraseña actual no es correcta.\n"
                        + "Verifiquela e intente nuevamente","Acción invalida",javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } catch (java.sql.SQLException ex) {
//            java.util.logging.Logger.getLogger(PanelConfigPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Conexión no establecida con la base de datos.\nIntentelo más tarde","Conexión Fallida",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean verificFields(){
        return ((jTextFieldActual.getText().compareTo("") != 0) && (jTextFieldNew.getText().compareTo("") != 0) && (jTextFieldConfir.getText().compareTo("") != 0));
    }
    
    public void resetField(){
        this.jTextFieldActual.setText("");
        this.jTextFieldNew.setText("");
        this.jTextFieldConfir.setText("");
    }
    
    private void doClose(){
        parent.setVisible(true);
        parent.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelVeri;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldActual;
    private javax.swing.JTextField jTextFieldConfir;
    private javax.swing.JTextField jTextFieldNew;
    // End of variables declaration//GEN-END:variables
}
