/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prociencia2.views.panels;

/**
 *
 * @author Klac
 */
public class PanelInstructionInteres extends javax.swing.JPanel {

    /**
     * Creates new form PanelInstructionInteres
     */
    public PanelInstructionInteres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 255));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("CUESTIONARIO DE INTERESES PROFESIONALES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instrucciones");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel2.setText("<html><p>A continuación se presenta una lista de actividades comunes sobre las cuales puedes haber tenido ya<br/>alguna experiencia personal.<br/><br/>\nA medida que leas cada cuestión, piensa: <b>¿QUÉ TANTO ME AGRADA HACER ESTO?</b><br/><br/>\nLuego, selecciona un número de respuesta según se indica enseguida.<br/><br/>\nSi lo que expresa la cuestión te <b>desagrada mucho</b>, anota el número 1; en el caso que te <b>desagrade un poco</b>,<br/>anota el número 2; cuando te sea <b>indiferente</b>, anota el número 3; si te <b>agrada algo</b>, esto es, sólo en<br/>parte, escribe el número 4, y por último si lo que expresa la cuestión te <b>agrada bastante</b>, escribe el<br/>número 5.<br/><br/>\n1 significa: \"me desagrada mucho o totalmente\"<br/>\n2 significa: \"me desagrada algo o en parte\"<br/>\n3 significa: \"me es indiferente, pues ni me gusta ni me disgusta\"<br/>\n4 significa: \"me agrada algo o en parte\"<br/>\n5 significa: \"me agrada bastante\"<br/><br/>\nAntes de escribir cada número, procura recordar o imaginar en qué consiste la respectiva actividad. Es necesario<br/>que seas lo más sincero al contestar.<br/>\nProcura no equivocarte de cuadro, ni saltar ninguno de ellos; observa que se contesta de izquierda a derecha; cada<br/>cuadro tiene un número para indicar que ahí debe anotarse la respuesta a la cuestión del mismo número.<br/>\n<p/></html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
